import HeaderSesion from '@/components/HeaderSesion'

export const metadata = {
    title: 'Bistro POS',
    description: 'Generated by create next app',
  }
  
  export default function SesionLayout({ children }) {
    return (
        <section className='flex flex-col h-screen'>
          <HeaderSesion/>
          {children}
        </section>
    
    )
  }