import HeaderSesion from '@/components/HeaderSesion'

export const metadata = {
    title: 'Bistro POS',
    description: 'Generated by create next app',
  }
  
  export default function SesionLayout({ children }) {
    return (
      <html lang="en">
      
        <body className='flex flex-col h-screen'>
          <HeaderSesion/>
          {children}
        </body>
      </html>
    )
  }