export const metadata = {
  title: 'Bistro POS',
  description: 'Generated by create next app',
};

export default function DashboardLayout({ children }) {


  return (
   
      <section className='flex flex-col relative'>
          
            
              {children}
    
      </section>
   
  );
}
