import '@/styles/globals.css';

export const metadata = {
  title: 'Bistro POS',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='bg-[#e8e8e8]'>
        {children}
      </body>
    </html>
  );
}