import '@/styles/globals.css';
import "tw-elements-react/dist/css/tw-elements-react.min.css";

import { Roboto } from "next/font/google";
const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: 'Bistro POS',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        {children}
      </body>
    </html>
  );
}
