export const metadata = {
  title: 'Bistro POS',
  description: 'Generated by create next app',
};

export default function OrderLayout({ children }) {


  return (
   
      <section className="h-screen flex-1 flex flex-col justify-start bg-[#e8e8e8] overflow-hidden">
           
              {children}
           
      </section>
   
  );
}
