import SideNavbar from '@/components/SideNavBar';

export const metadata = {
  title: 'Bistro POS',
  description: 'Generated by create next app',
};

export default function DashboardLayout({ children }) {
  return (
    <section className='flex flex-row relative'>
      <SideNavbar />
      {children}
    </section>
  );
}
