//import SideBar from '@/components/SideBar';
import SideNavbar from '@/components/SideNavBar';

export const metadata = {
  title: 'Bistro POS',
  description: 'Generated by create next app',
};

export default function DashboardLayout({ children }) {


  return (
    <html lang='en'>
      <body className='flex flex-row relative'>
           
          
            <SideNavbar/>
          
            
      
            <div className='bg-[#e8e8e8] lg:w-[85%] h-screen lg:absolute lg:right-0'>
            {children}
            </div>
     
        
      </body>
    </html>
  );
}
